### ISSUE TITLE
press.html - update contact information

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/solus-site.github.io#45]
The press page still lists Josh as the contact. This should be updated to the appropriate email alias for the comms team.

**Comment by BraydenGirard** [comment]
I have a draft open here #52

**Comment by TraceyC77** [comment]
> @TraceyC77 what should this email alias be ?

I see this was answered in the PR but for completeness, we have the "comms" alias at getsol.us for the press address. Thanks for your work!
